on:
  - push

jobs:
  build:
    uses: ashep/ci/.github/workflows/go-build.yaml@v1
    with:
      dockerfile: Dockerfile
      registry_user: ${{ vars.REGISTRY_USER }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
